# Generated by Django 4.1.2 on 2023-02-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'drafted'), ('p', 'published')], default='d', max_length=1),
        ),
    ]
