# Generated by Django 4.1.2 on 2023-02-25 11:09

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_article_slug_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله'},
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'در انتظار'), ('p', 'منتشر شده')], default='d', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
