# Generated by Django 4.1.2 on 2023-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='first_app.category', verbose_name='دسته بندی'),
        ),
    ]
